---
title: "Resources"
css: styles.css
---

The ecological knowledge of Black, Indigenous, and People of Color (BIPOC) can consist of holistic practices that preserve cultural knowledge while simultaneously addressing environmental issues. This knowledge is often place-based and acquired collectively through generations via oral histories, artistry, and relationships. In order to work against the historic exclusion of BIPOC knowledge from academic spaces and restoration decision-making, we have crafted this working resource of published literature with the goal of making rich sources of knowledge from BIPOC communities more visible. We aim to actively cultivate this space to highlight the historic and ongoing contributions of BIPOC communities to the fields of land and resource stewardship and restoration.

If you would like to contribute a work that addresses BIPOC contribution to restoration knowledge and/or research works around the topic of BIPOC knowledge in restoration to the bibliography, please submit your work at [this link](https://docs.google.com/forms/d/e/1FAIpQLSfcQ6yGS5y9EZ2m4v2xwQcGIvPyiq9QrqbL8cSXDW3X83TtBQ/viewform?usp=sf_link). Once approved, it will published to the [literature log](https://docs.google.com/spreadsheets/d/1p8NfnnznttsGJbcK3wus514XqBzyS8e6iDXq1P3X_UE/edit?usp=sharing) embedded below.

<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vRIMt1F5YWr_tlR4c6tiP9V0i2_-C7YYsCmERhGOR6NmHBSa2902hn_l2a9_vg18Bxy0jCZiVRTh-rG/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false" width="800" height="600" target="blank" rel="noreferrer noopener">

</iframe>


